# -*- coding: utf-8 -*-
"""Worksheet3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZ0FVSDU2Tx82qxr2K7G5RcKw7_A6zsd
"""

#Sorting and Subsetting
#1
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

#2
df=pd.read_csv('/content/drive/MyDrive/Titanic-Dataset.csv')
df.info()

#Problem-1
#1
fare=df[['Fare']]
print(fare.head())

#2
class_age=df[['Pclass','Age']]
print(class_age.head())

#3
survived_gender=df[['Survived','Sex']]
print(survived_gender.head())

#Problem-2
#1
fare_gt_100=df[df['Fare']>100]
print(fare_gt_100)

#2
first_class=df[df['Pclass']==1]
print(first_class)

#3
female_under_18=df[(df['Age']<18)&(df['Sex']=='female')]
print(female_under_18)

#Problem-2
#1
fare_gt_100=df[df['Fare']>100]
print(fare_gt_100)

#2
first_class=df[df['Pclass']==1]
print(first_class)

#3
female_under_18=df[(df['Sex']=='female')&df['Age']==18]
print(female_under_18)

#Subsetting Rows by Categorical variables:
#1
embarked_c_or_s = df[df['Embarked'].isin(['C','S'])]
print(embarked_c_or_s)

#2
first_second_class=df[df['Pclass'].isin([1,2])]
print(first_second_class)

#3.2
df['Age']=df['Age'].fillna(df['Age'].median())

#1
df['fare_per_year']=df['Fare']/df['Age']
df.head()

#2
high_fare_age=df[df['fare_per_year']>5]
print(high_fare_age)

#3
high_fare_age_srt=high_fare_age.sort_values(by='fare_per_year',ascending=False)
print(high_fare_age_srt)

#4
result=high_fare_age_srt[['Name','fare_per_year']]
print(result)

#5
result.head(1)

# Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their class?

#1
df['Fare_per_class']=df['Fare']/df['Pclass']

#2
adult_males=df[(df['Sex']=='male')& (df['Age']==18)]

#3
adult_males_srt=adult_males.sort_values(by='Fare_per_class',ascending=False)

#4
result=adult_males_srt[['Name','Age','Fare_per_class']]

#5
print(result)

#3.3
# What percent of the total fare revenue came from each passenger class?

#1
total_fare=df['Fare'].sum()

#2
fare_class1=df[df['Pclass']==1]['Fare'].sum()
fare_class2=df[df['Pclass']==2]['Fare'].sum()
fare_class3=df[df['Pclass']==3]['Fare'].sum()

#3
fare_totals=[fare_class1,fare_class2,fare_class3]

#4
fare_percentages=[(fare/total_fare)*100 for fare in fare_totals]
print(fare_percentages)

#Percent of total passengers by age group

#1
def categorize_age(age):
  if age < 18:
    return 'child'
  elif age < 65:
    return 'adult'
  else:
    return 'senior'
df['Age_group']=df['Age'].apply(categorize_age)

#2
total_passengers = len(df)

#3
age_group_counts=df['Age_group'].value_counts()

#4
age_group_percent=(age_group_counts/total_passengers)*100
print(age_group_percent)